#!/usr/bin/env python3
"""Boot configuration for the Thor USB drive: kernel command line and a one-shot grub.cfg.

    thor_boot.py cmdline --proc-cmdline FILE --root-partuuid UUID [--extra ARG ...]
    thor_boot.py grub-cfg --entries ENTRIES.json [--default ID] > grub.cfg

The GRUB default is an entry that returns to JetPack (chainloading the NVMe's own boot loader), and
the fallback hands control back to the firmware (`exit 1`), which tries the next UEFI boot option.
A test entry runs only when named in grubenv `next_entry`, and GRUB clears that before booting it,
so a kernel that fails (panic=10 reboots it) comes back to JetPack on the next reset. No `devicetree` command: the kernel keeps the device tree UEFI hands over. grub-install
never writes UEFI variables (--removable --no-nvram).
"""
import argparse
import json
import re
import sys
from dataclasses import dataclass
from typing import Optional

PARTUUID_RE = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")
# Characters GRUB's parser would treat specially; kernel arguments on this board never need them.
UNSAFE_RE = re.compile(r"[$`;&|<>(){}\"'\\]")
RESERVED_IDS = {"firmware-next"}


def cmdline(proc_cmdline, root_partuuid, extra=()):
    """JetPack's booted command line with the root swapped, boot-loader profiling dropped, panic=10."""
    if not PARTUUID_RE.match(root_partuuid or ""):
        raise ValueError(f"not a PARTUUID: {root_partuuid!r}")
    tokens = [t for t in proc_cmdline.split()
              if not t.startswith(("root=", "bl_prof_", "panic="))]
    tokens = [f"root=PARTUUID={root_partuuid}"] + tokens + ["panic=10"] + list(extra)
    for t in tokens:
        if UNSAFE_RE.search(t):
            raise ValueError(f"unsafe kernel argument {t!r}")
    return " ".join(tokens)


@dataclass
class Entry:
    id: str
    title: str
    fs_uuid: str
    kernel: Optional[str]
    initrd: Optional[str]
    cmdline: str
    chainload: Optional[str] = None  # EFI application on fs_uuid to hand over to, instead of a kernel


def grub_cfg(entries, default="firmware-next"):
    ids = [e.id for e in entries]
    if len(set(ids)) != len(ids):
        raise ValueError("duplicate menu entry ids")
    if RESERVED_IDS & set(ids):
        raise ValueError(f"reserved menu entry id in {ids}")
    if default not in set(ids) | RESERVED_IDS:
        raise ValueError(f"default entry {default!r} is not in the menu")
    for e in entries:
        if not e.kernel and not e.chainload:
            raise ValueError(f"entry {e.id!r} has neither a kernel nor a chainload target")
    out = [
        "# Generated by thor_boot.py; RaytoneOS Omarchy Thor USB boot menu.",
        "set timeout=3",
        f'set default="{default}"',
        'set fallback="firmware-next"',
        "if [ -s $prefix/grubenv ]; then",
        "  load_env -f $prefix/grubenv",
        "fi",
        'if [ -n "${next_entry}" ]; then',
        '  set default="${next_entry}"',
        "  set next_entry=",
        "  save_env -f $prefix/grubenv next_entry",
        "fi",
        "",
    ]
    for e in entries:
        out += [
            f'menuentry "{e.title}" --id {e.id} {{',
            f"  search --no-floppy --fs-uuid --set=root {e.fs_uuid}",
        ]
        if e.chainload:
            out.append(f"  chainloader {e.chainload}")
        else:
            out.append(f"  linux {e.kernel} {e.cmdline}")
            if e.initrd:
                out.append(f"  initrd {e.initrd}")
        out += ["}", ""]
    out += [
        'menuentry "Continue to the next firmware boot option (JetPack on the internal NVMe)" --id firmware-next {',
        "  exit 1",
        "}",
        "",
    ]
    return "\n".join(out)


def grub_install_args(esp):
    return ["grub-install", "--target=arm64-efi", f"--efi-directory={esp}", f"--boot-directory={esp}/boot",
            "--removable", "--no-nvram"]


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    c = sub.add_parser("cmdline")
    c.add_argument("--proc-cmdline", required=True)
    c.add_argument("--root-partuuid", required=True)
    c.add_argument("--extra", action="append", default=[])
    g = sub.add_parser("grub-cfg")
    g.add_argument("--entries", required=True, help="JSON list of Entry fields")
    g.add_argument("--default", default="firmware-next")
    args = ap.parse_args(argv)
    try:
        if args.cmd == "cmdline":
            print(cmdline(open(args.proc_cmdline).read(), args.root_partuuid, args.extra))
        else:
            print(grub_cfg([Entry(**e) for e in json.load(open(args.entries))], default=args.default), end="")
    except ValueError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
