#!/usr/bin/env python3
"""Boot configuration for the Thor USB drive: kernel command line and a one-shot grub.cfg.

    thor_boot.py cmdline --proc-cmdline FILE --root-partuuid UUID [--extra ARG ...]
    thor_boot.py grub-cfg --entries ENTRIES.json --default ID > grub.cfg

The default is an entry that returns to JetPack (chainloading the NVMe's own boot loader). An entry
boots only after its filesystem is found and otherwise reboots, and the fallback reboots, so GRUB
never stops at a prompt. GRUB's exit is only a manual item: it returns EFI_SUCCESS, and edk2 then
opens its boot manager menu and waits. A test entry runs only when named in grubenv `next_entry`,
and only if clearing it with save_env succeeded first, so a kernel that fails (panic=10 reboots it)
comes back to the default on the next reset. No `devicetree` command: the kernel keeps the device tree UEFI hands over. grub-install
never writes UEFI variables (--removable --no-nvram).
"""
import argparse
import json
import re
import sys
from dataclasses import dataclass
from typing import Optional

PARTUUID_RE = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")
# Characters GRUB's parser would treat specially; kernel arguments on this board never need them.
UNSAFE_RE = re.compile(r"[$`;&|<>(){}\"'\\]")
ID_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")
TITLE_RE = re.compile(r"^[A-Za-z0-9 .,:()/_+-]+$")
FS_UUID_RE = re.compile(r"^[0-9A-Fa-f][0-9A-Fa-f-]{3,40}$")
PATH_RE = re.compile(r"^/[A-Za-z0-9._/+-]+$")
# Appended to every menu. "retry-reboot" is the fallback. "uefi-menu" is for a person only: GRUB's
# exit returns EFI_SUCCESS and edk2 then opens its boot manager menu and waits.
RESERVED_IDS = ("retry-reboot", "uefi-menu")


def cmdline(proc_cmdline, root_partuuid, extra=()):
    """JetPack's booted command line with the root swapped, boot-loader profiling dropped, panic=10."""
    if not PARTUUID_RE.match(root_partuuid or ""):
        raise ValueError(f"not a PARTUUID: {root_partuuid!r}")
    tokens = [t for t in proc_cmdline.split()
              if not t.startswith(("root=", "bl_prof_", "panic="))]
    tokens = [f"root=PARTUUID={root_partuuid}"] + tokens + ["panic=10"] + list(extra)
    for t in tokens:
        if UNSAFE_RE.search(t):
            raise ValueError(f"unsafe kernel argument {t!r}")
    return " ".join(tokens)


@dataclass
class Entry:
    id: str
    title: str
    fs_uuid: str
    kernel: Optional[str]
    initrd: Optional[str]
    cmdline: str
    chainload: Optional[str] = None  # EFI application on fs_uuid to hand over to, instead of a kernel


def _check_entry(e):
    if not ID_RE.match(e.id):
        raise ValueError(f"bad entry id {e.id!r}")
    if not TITLE_RE.match(e.title):
        raise ValueError(f"bad title for {e.id}: {e.title!r}")
    if not FS_UUID_RE.match(e.fs_uuid):
        raise ValueError(f"bad filesystem UUID for {e.id}: {e.fs_uuid!r}")
    if not e.kernel and not e.chainload:
        raise ValueError(f"entry {e.id!r} has neither a kernel nor a chainload target")
    for path in (e.kernel, e.initrd, e.chainload):
        if path is not None and not PATH_RE.match(path):
            raise ValueError(f"bad path for {e.id}: {path!r}")
    for token in e.cmdline.split():
        if UNSAFE_RE.search(token):
            raise ValueError(f"unsafe kernel argument for {e.id}: {token!r}")


def grub_cfg(entries, default):
    ids = [e.id for e in entries]
    for e in entries:
        _check_entry(e)
    if len(set(ids)) != len(ids):
        raise ValueError("duplicate menu entry ids")
    if set(RESERVED_IDS) & set(ids):
        raise ValueError(f"reserved menu entry id in {ids}")
    if default not in ids:
        raise ValueError(f"default entry {default!r} is not one of {ids}")
    fallback = len(entries)  # retry-reboot comes right after the caller's entries
    out = [
        "# Generated by thor_boot.py; RaytoneOS Omarchy Thor USB boot menu.",
        "set timeout=3",
        f'set default="{default}"',
        f'set fallback="{fallback}"',
        "if [ -s $prefix/grubenv ]; then",
        "  load_env -f $prefix/grubenv next_entry",
        "fi",
        'if [ -n "${next_entry}" ]; then',
        '  set try_entry="${next_entry}"',
        "  set next_entry=",
        "  if save_env -f $prefix/grubenv next_entry; then",
        '    set default="${try_entry}"',
        "  fi",
        "fi",
        "",
    ]
    for e in entries:
        out += [
            f'menuentry "{e.title}" --id {e.id} {{',
            f"  if search --no-floppy --fs-uuid --set=root {e.fs_uuid}; then",
        ]
        if e.chainload:
            out.append(f"    chainloader {e.chainload}")
        else:
            out.append(f"    linux {e.kernel} {e.cmdline}".rstrip())
            if e.initrd:
                out.append(f"    initrd {e.initrd}")
        out += [
            "    boot",
            "  fi",
            f'  echo "RaytoneOS: could not boot {e.id}; rebooting in 10 seconds"',
            "  sleep 10",
            "  reboot",
            "}",
            "",
        ]
    out += [
        'menuentry "Reboot and try again" --id retry-reboot {',
        '  echo "RaytoneOS: rebooting in 10 seconds"',
        "  sleep 10",
        "  reboot",
        "}",
        "",
        'menuentry "UEFI boot manager (for a person at the keyboard)" --id uefi-menu {',
        "  exit",
        "}",
        "",
    ]
    return "\n".join(out)


def grub_install_args(esp):
    return ["grub-install", "--target=arm64-efi", f"--efi-directory={esp}", f"--boot-directory={esp}/boot",
            "--removable", "--no-nvram"]


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    c = sub.add_parser("cmdline")
    c.add_argument("--proc-cmdline", required=True)
    c.add_argument("--root-partuuid", required=True)
    c.add_argument("--extra", action="append", default=[])
    g = sub.add_parser("grub-cfg")
    g.add_argument("--entries", required=True, help="JSON list of Entry fields")
    g.add_argument("--default", required=True)
    args = ap.parse_args(argv)
    try:
        if args.cmd == "cmdline":
            print(cmdline(open(args.proc_cmdline).read(), args.root_partuuid, args.extra))
        else:
            print(grub_cfg([Entry(**e) for e in json.load(open(args.entries))], default=args.default), end="")
    except ValueError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
